name: 'Grundspiel'
authors:
  - 'BixelPitch'
original: false
translation: 'en/Base Game'
language: 'de'
black_cards:
  - Hey Reddit! Ich bin ___. Frag mich irgendwas.
  - Ich präsentiere X-treme Baseball! Es ist wie normales Baseball, aber mit ___!
  - Was ist Batmans Guilty Pleasure?
  - Die Transportsicherheitsbehörde verbietet neuerdings ___ in Flugzeugen.
  - Als der Pharao sich unbeeindruckt zeigte, rief Moses die Plage ___ herbei.
  - Nur ein Mal würde ich von dir hören wollen “Danke, Mama. Danke für ___.”
  - Papa, warum weint Mama?
  - Als ich auf ACID war, wurde ___ zu ___.
  - "Neues von J. K. Rowling: Harry Potter und die Kammer des ___."
  - Es stimmt, ich habe ___ getötet. Wie, fragst du? ___.
  - Es tut mir Leid Professor, ich konnte meine Hausaufgaben nicht machen wegen ___.
  - Und der Oscar für ___ geht an ___.
  - 50% aller Ehen enden in ___.
  - "Meine lieben Amerikaner: Bevor Ende dieses Jahrzehnts, werden wir ___ auf dem Mond haben!"
  - "Diese Staffel bei Steppenwolf, Samuel Beckett’s klassisches dramatisches Schauspiel: Warten auf ___." ###
  - An Stelle von Kohle gibt der Weihnachtsmann bösen Kindern nun ___.
  - Alter, geh' nicht ins Badezimmer. Da ist ___ drin.
  - Wie habe ich meine Jungfräulichkeit verloren?
  - Es ist eine Schande, dass Kinder heutzutage alle mit ___ in Berührung kommen.
  - "Schritt 1: ___.\nSchritt 2: ___.\nSchritt 3: Profit."
  - Das Leben der amerikanischen Ureinwohner wurde für immer verändert, als der weiße Mann ihnen ___ zeigte.
  - Welche Lehre benutzt Amerika, um Studenten zum Erfolg zu inspirieren? ###
  - Vielleicht wurde sie damit geboren. Vielleicht ist es ___.
  - Was denkt George W. Bush wohl gerade?
  - ___. Wetten du willst mehr davon?
  - Kinder, ich brauche keine Drogen um high zu werden. Ich bin high von ___.
  - Für meinen nächsten Zaubertrick, werde ich ___ aus meinem ___ ziehen.
  - Während die Vereinigten Staaten und die Soviet Union sich den Wettlauf ins All lieferten, pumpte die mexikanische Regierung Millionen von Pesos in die Erforschung von ___.
  - Weiße mögen ___.
  - ___ ist eine gefährliche Sache, die unweigerlich zu ___ führt.
  - Wieso tut mir alles weh?
  - Ein romatische Abendessen bei Kerzenschein wäre nicht das Gleiche ohne ___.
  - In einem Disney Channel Originalfilm, kämpft Hannah Monta zum ersten Mal mit ___.
  - Was ist meine geheime Kraft?
  - Ich mache eine Diät diese Woche. Nichts außer Grünkohlsaft und ___.
  - ___ + ___\n= ___.
  - "Habe gerade dieses verstörende Video gesehen! Bitte retweeten!! #stop___"
  - Kleiner Tip! Wenn dein Mann dich fragt, ob du ihm einen blasen willst, versuche ihn stattdessen mit ___ zu überraschen.
  - Der Wandertag wurde völlig ruiniert wegen ___.
  - Was ist der beste Freund einer Frau?
  - Liebe Abby,\nIch habe etwas Probleme mit ___ und ich brauche deinen Rat.
  - In M. Night Shyamalan’s neuen Film, findet Bruce Willis heraus, dass ___ in Wirklichkeit die ganze Zeit ___ war.
  - Wenn ich Bundeskanzler bin, werde ich das Ministerium für ___ gründen.
  - Was verheimlichen meine Eltern vor mir?
  - Ich bin zwar kein Arzt, aber ich bin mir sicher, dass man das worunter du leidest “___” nennt.
  - Was gibt es tonnenweise im Himmel?
  - "Nach vier Platin-Alben und drei Grammys ist es Zeit zu meinen Wurzeln zurück zu kehren zu dem, was mich in erster Linie dazu inspiriert hat Musik zu machen: ___."
  - Was ist ein Garant dafür flachgelegt zu werden?
  - Was funktioniert immer um eine Party anzuheizen?
  - WENN du ___ magst, BIST DU VIELLEICHT EIN NAZI.
  - Mach ein Haiku.
  - Was machte meinen ersten Kuss so unangenehm?
  - Sie sagten wir seien verrückt. Sie sagten wir können nicht ___ in ___ stecken. Sie lagen falsch.
  - "Lifetime® präsentiert “___: die Geschichte von ___.”"
  - "___: von Kindern getestet, von Müttern freigegeben."
  - Warum kann ich nachts nicht schlafen?
  - Willkommen bei Burger King. Möchten sie ihren Abend gleich mit ___ starten?
  - Ich habe 99 Probleme, aber ___ ist keins davon.
  - ___. Es ist 'ne Falle!
  - RTLs neue Reality Show zeigt acht waschechte Promis, wie sie mit ___ leben.
  - Was ist das für ein Geruch?
  - Nach acht Jahren im Weißen Haus, wie kann Obama endlich loslassen? ###
  - So endet die Welt.\nSo endet die Welt.\nNicht mit einem lauten Knall, sondern mit ___.
  - "Demnächst auf dem Broadway, ___: Das Musical."
  - Was würde Oma verstören, aber auf seltsame Weise anziehend finden?
  - ___. Das war so Metal.
  - Ich habe ___ nie wirklich verstanden, bis ich auf ___ gestoßen bin.
  - Ich mag es beim Sex an ___ zu denken.
  - Hier ist die Kirche\nHier der Kirchturm\nÖffne die Türen, dort ist ___.
  - Bevor ich sie töte Mr. Bond, muss ich ihnen ___ zeigen.
  - Eine kürzlich durchgeführte Labor-Studie zeigt, dass Studenten ohne Abschluss 50% weniger Sex haben, nachdem sie ___ ausgesetzt worden sind.
  - Ich präsentiere das neue Superhelden/Gehilfen Duo! Es ist ___ und ___!
  - Was hat meine letzte Beziehung beendet?
  - Was ist das für ein Geräusch?
  - Ähm, hey Leute. Ich weiß es war meine Idee, aber ich habe ernste Zweifel an ___.
  - Warum bin ich so klebrig?
  - "Demnächst auf DMAX: Die Weltmeisterschaft von ___."
  - Wenn ich Milliardär bin, werde ich ein 15 Meter große Statue errichten lassen zu Ehren von ___.
  - Militärhistoriker schätzen Alexander den Großen für seine brillante Idee ___ gegen die Perser einzusetzen.
  - Krieg! Wofür ist er gut?
white_cards:
  - Stille
  - Die Illusion eine Wahl zu haben in einer kapitalistischen Gesellschaft im Endstadium
  - Viele Fledermäuse
  - Hungersnot
  - Fleischfressende Bakterien
  - Fliegende Sex-Schlangen
  - Einen Scheiß auf die dritte Welt geben
  - Magneten
  - Gestaltenwandler
  - Schauen was passiert, wenn man Leute in einen Raum voller hungriger Möwen sperrt
  - Eine Kreuzigung
  - Jennifer Lawrence
  - 72 Jungfrauen
  - Ein Livekonzert-Publikum
  - Ein Zeitreiseparadoxon
  - Authentische mexikanische Küche
  - Staftaten begehen
  - Synergetische Management-Lösungen
  - Erdrückendee Schulden
  - Vaterkomplexe
  - Getragene Unterwäsche
  - Ein Furz der so kräftig ist, dass er Riesen von ihren 1000 jährigen Schlummer aufweckt
  - Der ehemalige Präsident George W. Bush
  - Full frontal nudity
  - Sanfter Kuschelsex
  - BATMAN
  - Landwirtschaft
  - Gerade so 20.000€ im Jahr machen
  - Mich selbst mit Parmesan und Chiliflocken einreiben weil ich 'ne Pizza bin
  - Ein Ei legen
  - Ausziehen und Nickelodeon gucken
  - Vorgeben sich zu kümmern
  - Natürliche Selektion
  - Kleiderbügelabtreibungen
  - Sex mit Patrick Stewart
  - Mein misshandelnder Freund, der eigentlich gar nicht so böse ist wenn man ihn richtig kennt
  - Große Träume haben aber kein realistischen Weg, um sie zu erreichen
  - Oma nackt sehen
  - Popel
  - Der unausweichliche Hitzetod des Universums
  - Verschreibungspflichtige Schmerztabletten
  - Schlagen
  - Mansplaining
  - Eine homoerotische Volleyball-Montage
  - Das Wunder der Geburt
  - Die Begeisterung
  - Es ausfechten
  - Privilegien der Weißen
  - Anton Hofreiter
  - Sachen hinstellen, wo sie hingehören
  - Fragile Maskulinität
  - All-you-can-eat Shrimps für 6,99€
  - Aus dem Meer hervorkommen und Amok durch Tokyo laufen
  - Ronald Mc Donald
  - AXE Deo
  - Das Blut Christi
  - Ein halbtoter alter Mann
  - Kanye West
  - Heißer Käse
  - Raptorenattacken
  - 7 Tote und 3 Schwerverletzte
  - Smegma
  - Alkoholismus
  - Ein mittelalter Mann auf Rollschuhen
  - Die Vergangenheit
  - Meine Genitalien
  - Ein endloser Strom aus Durchfall
  - Wissenschaft
  - In den Spiegel schauen, Lippenstift auftragen und flüstern “Heute Nacht wirst du Sex mit Tom Cruise haben.”
  - Brandschatzen und Plündern
  - Ein übergroßer Lollipop
  - Selbshass
  - Oralsex nicht erwiedern
  - Flugunfähige Vögel
  - Ein guter Schnupfer
  - 50.000 Volt direkt auf die Nippel
  - Auf meinem Gesicht sitzen und mich als Abfall bezeichnen
  - Halbherziges Vorspiel
  - Die Bibel
  - Deutscher Kerkerporno
  - Ein ausgewogenes Frühstück
  - Tote Vögel überall
  - Das eintreffen der Pizza
  - Permanentes Orgasmus-Gesicht-Syndrom
  - In Flammen stehen
  - Teenager Schwangerschaft
  - Gandhi
  - Dein komischer Bruder
  - Der kalte, erfrischende Geschmack von Pepsi®
  - Chemiewaffen
  - Oprah
  - Sich wundern, ob man noch etwas von der Salsa to-go bekommen kann
  - Eine Fleshlight®
  - Eine Pyramide aus abgeschlagenen Köpfen
  - Eine Erektion, die länger als vier Stunden anhält
  - Einen Dreier mit meiner Frau und Shaquille O’Neal
  - Bananen
  - Passiv aggressive Post-its
  - Hillary Clintons E-Mails
  - Zur HUK wechseln
  - Ein wenig pinkeln
  - Feuchte Träume
  - Die Juden
  - Mein fremdgehender Hurensohn-Ehemann
  - Armut
  - Kamikaze-Piloten
  - Selbstmord begehen
  - Die homosexuelle Agenda
  - Kräftige Oberschenkel
  - Diese Schlampen
  - Der einzig homosexuell Mensch in 100 Kilometern
  - Das erste Mal haben
  - Ein Mexikaner
  - Ein Falke mit einer Kappe auf dem Kopf
  - Zauberer-Musik
  - Paula die Kuh
  - Donald J. Trump
  - Oma auf die Stirn küssen und den Stecker ziehen
  - Sexuelle Anziehung
  - Ein AR-15 Sturmgewehr
  - Juuling
  - Kostenlose Probem
  - Meinen engsten Kreis verletzen
  - Das Richtige tun
  - Mein guter BH
  - Einen Kongressabgeordneteen ins Gesicht schlagen
  - Kitekat
  - Reich sein
  - Ein dreifünftel Kompromiss
  - Laktation
  - Weltfrieden
  - Die Fresse halten damit ich das Spiel sehen kann
  - Süße, süße Rache
  - Republikaner
  - Meine Füße riechen und küssen
  - Eine sehr viel jüngere Frau
  - Ein hartgekochtes Ei aus dem Arschloch meines Mannes essen
  - RoboCop
  - Eine heraushängende Titte
  - Justin Bieber
  - Oompa-Loompas
  - Unangebrachtes Jodeln
  - Pubertät
  - Geistere
  - Einen Rülps erwarten und auf den Fußboden kotzen
  - Adderall®
  - The Red Hot Chili Peppers
  - Sideboob
  - 50 mg Sertralin täglich
  - Meine Schwester ficken
  - 3 Penisse zu einem Zopf flechten
  - Virtuose Jazz Hände
  - Ein Oktopus, der sieben Handjobs gibt und eine Zigarette raucht
  - My neck, my back, my pussy, and my crack
  - J. D. Power and his associates ###
  - Mundherpes
  - Gefingert werden
  - Mein Uber-Fahrer, Pavel
  - Müller mit der Ecke
  - Polizeigewalt  
  - Pottwale
  - Schwarze Frauen
  - Auf gesunde Weise über ihre Gefühle sprechende Männer
  - Inzest
  - Meine Tasche füllen mit Sachen von der Arbeit
  - Vorpubertäre
  - Meine fette Tochter
  - Rap Musik
  - Pac-Man der unkontrolliert Sperma frisst
  - Ganz lässig einen Dreier vorschlagen
  - Spermaknappheit
  - Gott
  - Abdriften in die Bedeutungslosigkeit
  - Darth Vader
  - Ein trauriger Handjob
  - Genau das was man erwarten würde
  - Die Wunder des Orients
  - Sexuelles Pinkeln
  - Emotionen
  - Sachen anlecken, damit sie einem gehören
  - Arbeit
  - Die Plazenta
  - Spontane Menschenverbrennung
  - Das Bachelorette Staffelfinale
  - Ein kleines Pferd
  - William Shatner
  - Crack an Kinder verkaufen
  - Ein M. Night Shyamalan Plot Twist
  - Einen Mann mit Trauben bewerfen bis er den Bezug zur Realität verliert
  - Dominanz aufbauen
  - Fingermalen
  - Geruch alter Leute
  - Braune Menschen
  - Mutwillige Zerstörung
  - Pädophile
  - Hefe
  - Von einem Verkaufsautomaten zermatscht werden
  - Meine inneren Dämonen
  - Eine Super Soaker™ voller Katzenpisse
  - Aaron Burr
  - Meine böse Tochter, die ihre Tanzvorstellung verkackt hat
  - Rechtecke
  - Katapulte
  - Arme Menschen
  - Kuscheln
  - So viel Graß, wie man mit 20€ kaufen kann
  - Kriegsamputationen
  - Spaghetti? Schon wieder?
  - Ausschließlich Asiatinnen daten
  - Betrug
  - Macht
  - Wie geil es ist auf Pilze zu sein
  - Ronald Reagan
  - Eine enttäuschende Geburtstagsparty
  - Nachos für auf den Tisch
  - Eine Blaubeere wereden
  - Jeden verurteilen
  - Kourtney, Kim, Khloe, Kendall, und Kylie
  - Heiraten, Kinder haben, Zeug kaufen, auf Mallorca zur Ruhe setzen und sterben
  - Verdammte Ruhe und Frieden
  - AIDS
  - Bilder von Brüsteen
  - Starke weibliche Charaktere
  - Etwas Foundation, Maskara und ein klein wenig Rouge
  - Von Sperma bespritzt werden
  - Verpixelte Bukkake
  - Eine Lebenslänge Traurigkeit
  - Einen ganzen Tag ohne Masturbation verbringen
  - Hospitzpflege
  - Richtig High werden
  - Die Opiumepidemie
  - Penisneid
  - Pimmelbilder
  - Rassismus
  - Menstrualer Wutanfall
  - Sonnenschein und Regenbogen
  - Schwulen-Konversions-Therapie
  - Richter Alexander Holdt, der brutal auf deinen Penis einhämmert
  - Kanzlerin Angela Merkel
  - Der KKK
  - Radikaler Islamistischer Terror
  - Großer Bizeps
  - Mein kleiner Ständer
  - Würgen
  - Ein pangender Oktopus, der auf der Suche nach Liebe den Kosmos durchstreift
  - Meth
  - Leibeibeigenschaft
  - Ein Kind unten halten es anfurzen
  - Ein spinnenfadenartiger Strahl aus Sperma, der vom Licht berüht wird, während er durch die frische Morgenluft weht
  - Stündliches umbringen von Geiseln
  - Die Rhytmen von Afrika
  - In Singen und Tanzen ausbrechen
  - Ein Bop It™
  - Ein ganzes Stück Butter
  - Immer noch Jungfrau sein
  - Problemlösung mit Gewalt
  - Lepra
  - Gloryholes
  - Nippelwetter
  - Das Herz eines Kindes
  - Welpen!
  - Jesus Jünger 
  - Kleine Jungenpenisse
  - Auf einem ALDI-Parkplatz halbnackt aufwachen
  - Der Pabst
  - Weiße Menschen
  - Tentakelporno
  - Mein helles, pinkes Fickloch
  - Eine alte Frau die weiß, wie man mit einem Penis umgeht
  - Die Drogen von der Straße kriegen, direkt in meinen Körper
  - Daniel Radcliffes leckeres Arschloch
  - Aktives Zuhören
  - So tief ich meinen eigenen Penis in meinen Arsch reinbekomme
  - Rosetten als Augen haben
  - Das Flötensolo von “MyHeart Will Go On”
  - Seppuku
  - Ethnische Säuberung
  - Juckende Muschi
  - Meinen Freund so hart blasen, sodass er einscheißt
  - Eine verdammt große Menge Mandeln
  - Danny DeVito
  - Die Magie des Theaterspiels
  - Eine Jungfrau in einen Vulkan schmeißen
  - Dwayne “The Rock” Johnson
  - Einen Salat für Männer, bestehend aus Metall
  - Sich auf die Ehe aufspareen
  - Ungeheure Dummheit
  - Glänzende Dinge
  - Dinge akzeptieren so wie sie sind
  - NBA Superstar LeBron James
  - Ihren Problemen lauschen ohne zu versuchen sie zu lösen
  - Therapie
  - Der Teufel höchst persönlich
  - Autokannibalismus
  - Erektile Disfunktion
  - Meine Sammlung an japanischen Sextoys
  - Fett und dumm sein
  - Kreuz und quer scheißen
  - Für immer
  - Diesen Arsch aufreißen als wäre es Geschenkpapier
  - Mehr Schwanz bekommen als abgemacht war
  - Eine salzige Überraschung
  - Der Osten
  - The violation of our most basic human rights
  - Tap dancing like there’s no tomorrow
  - A bowl of mayonnaise and human teeth
  - Fiery poops
  - Saying “I love you”
  - Inserting a Mason jar into my anus
  - Consensual sex
  - Telling a shitty story that goes nowhere
  - A good, strong gorilla
  - Seeing my father cry
  - The true meaning of Christmas
  - Some of the best rappers in the game
  - Owning and operating a Chili’s franchise
  - Estrogen
  - Necrophilia
  - Being a woman
  - Getting into a pretty bad car accident
  - Bill Nye the Science Guy
  - Girls
  - The Russians
  - A bleached asshole
  - Fucking the weatherman on live television
  - Black people
  - The Boy Scouts of America
  - Lunchables™
  - Bitches
  - PTSD
  - Dark and mysterious forces beyond our control
  - Smallpox blankets
  - Masturbating
  - Some punk kid who stole my turkey sandwich
  - Heartwarming orphans
  - Spirit Airlines
  - Bubble butt bottom boys
  - Hobos
  - Queefing
  - The guys from Queer Eye
  - Cardi B
  - Viagra®
  - Soup that is too hot
  - Muhammad (Peace Be Upon Him)
  - Explaining how vaginas work
  - Doin’ it in the butt
  - My ex-wife
  - Teaching a robot to love
  - Touching a pug right on his penis
  - AcademyAward winnerMeryl Streep
  - Drinking alone
  - Dick fingers
  - Multiple stab wounds
  - A windmill full of corpses
  - Count Chocula
  - Vladimir Putin
  - The Patriarchy
  - Poopy diapers
  - Child abuse
  - Anal beads
  - Slaughtering innocent civilians
  - The glass ceiling
  - Vomiting seafood and bleeding anally
  - The American Dream
  - Not wearing pants
  - Pulling out
  - Being able to talk to elephants
  - Horse meat
  - A really cool hat
  - My balls on your face
  - Pooping in a laptop and closing it
  - Dead babies
  - Foreskin
  - Stalin
  - A stray pube
  - Worshipping that pussy
  - Completely unwarranted confidence
  - A saxophone solo
  - Italians
  - A fetus
  - Firing a rifle in to the air while balls deep in a squealing hog
  - Mike Pence
  - 10,000 Syrian refugees
  - Forced sterilization
  - My relationship status
  - Nicolas Cage
  - Child beauty pageants
  - Explosions
  - Not vaccinat in gmy children because I am stupid
  - An unwanted pregnancy
  - Diversity
  - A white ethno state
  - Bees?
  - Lena Dunham
  - Huffing spray paint
  - A man on the brink of orgasm
  - Repression
  - Harry Potter erotica
  - Giving birth to the Antichrist
  - Three dicks at the same time
  - Nazis
  - Invading Poland
  - My vagina
  - Assless chaps
  - Murder
  - 8 oz of sweet Mexican black-tar heroin
  - What that mouth do
  - Dead parents
  - Object permanence
  - Giving 110%
  - Her Majesty, Queen Elizabeth II
  - The Trail of Tears
  - Memes
  - Opposable thumbs
  - Racially-biased SAT questions
  - The Great Depression
  - Chainsaws for hands
  - Sex with animals
  - Being marginalized
  - Goblins
  - Hope
  - Liberals
  - A micropenis
  - My soul
  - A ball of earwax, semen, and toenail clippings
  - Illegal immigrants
  - Elderly Japanese men
  - The female orgasm
  - Hetero normativity
  - A horde of Vikings
  - Hot people
  - Seething with quiet resentment
  - An Oedipus complex
  - Crumbs all over the god damn carpet
  - Arnold Schwarzenegger
  - The wifi password
  - Spectacular abs
  - Geese
  - Extremely tight pants
  - Fox News
  - A little boy who won’t shut the fuck up about dinosaurs
  - A bird that shits human turds
  - A mopey zoo lion
  - A bag of magic beans
  - Poor life choices
  - Making a pouty face
  - Vehicular mans laughter
  - Women’s suffrage
  - Some guy
  - My sex life
  - Auschwitz
  - A snapping turtle biting the tip of your penis
  - All the dudes I’ve fucked
  - Judge Judy
  - African children
  - This month’s mass shooting
  - Barack Obama
  - The clitoris
  - The Big Bang
  - Land mines
  - The entire Mormon Tabernacle Choir
  - A micro pig wearing a tiny rain coat and booties
  - Penis breath
  - Jerking off into apool of children’s tears
  - Man meat
  - Farting and walking away
  - Being a dick to children
  - One trillion dollars
  - Drowning the kids in the bathtub
  - Me time
  - The Underground Railroad
  - Poorly-timed Holocaust jokes
  - A sea of troubles
  - Dying
  - Drinking out of the toilet and eating garbage
  - The gays
  - The screams
  - The terrible screams
  - Lumberjack fantasies
  - Morgan Freeman’s voice
  - Women in yogurt commercials
  - Natural male enhancement
  - Men
  - The bombing of Nagasaki
  - Fake tits
  - The Amish
  - Being a mother fucking sorcerer
  - My black ass
  - Genuine human connection
  - Announcing that I am about to cum
  - David Bowie flying in on a tiger made of lightning
  - My ugly face and bad personality
  - A bitch slap
  - A brain tumor
  - Balls
  - Grandma
  - Friction
  - Chunks of dead hitchhiker
  - Fear itself
  - Jews, gypsies, and homosexuals
  - The milkman
  - Cards Against Humanity
